# Default values for ibm-cloud-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

services:
  -
    name: "cloudant-helm-roder"
    serviceClass: "cloudantnosqldb"
    # the plan to use for the service.  For creating a service that maps to an existing service use "Alias" and also specify an instanceId.
    plan: "standard"
    tags:
      - foo
      - bar
    # Provide an instanceId if you want to define a service that maps to an existing service instead of creating a new one.
    # Note: The instanceId is only applied to the template if the plan is set to Alias.  Otherwise it is omitted, even it specified here.
    # instanceId: "crn:v1:bluemix:public:language-translator:us-south:a/0b5a00334eaf9eb9339d2ab48f20d7f5:e641000a-9108-45fb-b2e6-ab7e52acc962::"
    parameters:
      # Allowed values are "public", "private" and "public-and-private".
      service_endpoints: private
