{{- range .Values.services}}
---
  {{- $name := (required "name is required." .name) }}
{{- if not .bindingAlias }}
  {{- $serviceClass := (required "serviceClass is required." .serviceClass) }}
  {{- $plan := (required "plan is required." .plan) }}
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: {{ $name }} {{- if eq $plan "Alias" -}} -alias {{- end }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  {{- if eq $plan "Alias" }}
  annotations:
    ibmcloud.ibm.com/instanceId: {{ required "instanceId is required for plan type \"Alias\"." .instanceId }}
  {{- end }}
spec:
  plan: {{ $plan }}
  serviceClass: {{ $serviceClass }}
  externalName:  {{ $name }}
  context:
    region: {{ default "us-south" .region }}
    {{- if .resourceGroup }}
    resourceGroup: {{ .resourceGroup }}
    {{- end -}}
  {{ include ( printf "ico.%s.spec" $serviceClass ) . | indent 4 }}
---
{{- else }}
{{- end }}
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: {{ $name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  {{- if .bindingAlias }}
  annotations:
    ibmcloud.ibm.com/keyId: {{ required "keyId is required for bindingAlias." .keyId | quote }}
  {{- end }}
spec:
  serviceName: {{ .name }} {{- if .bindingAlias -}} -alias {{- end }}
  role: {{ default "Manager" .role }}
  {{- if .namespace }}
  serviceNamespace: {{ .namespace }}
  {{- end }}
  {{- if .bindingAlias }}
  alias: {{ .bindingAlias }}
  {{- end }}
{{- end }}
